language: node_js
node_js: node
script:
- npm run lint
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUI
  - REPO_NAME=dropdown
  - secure: vmqM13ByJGZquFtfVpd3iGjVaKLYzBljWuOz8Eo5pYb1JmZV4lWC682rXt/bnTsvBwJyi5Gfg4+om2auKv8Q6OLVFakjCm+5ySjY8Fe7F66pQZv0i07UxSdmEBYRHzanpkApUFDqUuisy91DSJ5lInW0u/XuQZaVPeeyOpgdOag6lEocxAU1TbrFKEwe4dgywvSaRvwWPosXcXOWe5KjSkK44wK09bDhGb2b/vnjmSCbLKGF+odSy4RubRIOhIBvG7WXfLE58u7fuM2CbNseepWQjo6wIEB409d9OGYklYkCi4S6Tloo+eqsuj6r1qruhAQHM+et0vp959OIEPU+8QUAYhcXeRPROpFpY9ATUuwrdeUc4CzwXRNf1ENqNOJj5j53vHOZhaqx7M5XnhKtPRBgzi990r31/qAo/AL84FCiVRdPhBXv/H/msFJUbkaqYvmaA5+nB+ZRNU5ceIXplh6jm1pMajTsVnxdspxnanAPv26+REWXBPJoKz/LDsBaL4/iSeY55CZFN5EojDmxBzpuSl4OWuB5/6cWxgQoPMHWLdrZwr167L1KEdbhmH9PrJNaqd9b4Yegq4hWX21Kjcy1nMcG4wShCtYijV3wXZ1vh3jvA8/dm/fSINfMC3T/CZZVJSPvcLM6711Dec+JeWwIsbCTXzJzDCwuyqnbcTQ=
