language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: rjj1wnDSPijveGM36VrDHo8NBC1V1PdjjYkg4eAfD1UCsAqtcZQrzlFncKpd6AozHT2La6XigHrINT53CEAFJ1eD9d/nFOqusDSxhsAq92YmZ3a4h5+8Bc/iVk7cSfvNK07ALv9CvYocgzIBceisB4mrHm1h22AXeg8NrJGZuPFXesOnVmbTg02yy+FmD1go0cvxQNLcuR7lUYURDfjg9u/hzooNTxfIesfi8Tdj3HWFZSDPFmIH3QYAZcMJp60zAi3p33p4SbcrXYy3dxjqLLHnShd33Oi8rqjgMAKHCVXdSqqmfUmBBdfn0TjUDVluNYb/xSjJ2kBuiOvLkeXjmySk5vtjfloAJOKrGC8F7Gg+TThkOf4Ry7jfQZRDGCWRSYaq3vsquXPUfXrS5AojL0s+1AlaESFPAEUPg5kcWSM45J8io9nS9x35y5qZgARm1Lny3YBONTQbPk9NqCHxbKZqCY7BjpMNtBDcXWSeeaCieX7qsRuGZdoBON/zD4fG7D9kowdEYogGu1BGimTkR+g3DdQcb+l3gYH2JUnXogxbqvCeU3lKKABT59rTamKl9B9HO/C/tgwvkW+fhxC+AUF9b4sQ2RZcWoeel8V9Fe5hEM9f9Rb2xkGN8krA07u9daJWNeZKXzwrV8iiQeZD2o5grB/5ZEnM/QXT8CDHvFA=
